import { PasswordType } from "@/types/profile";

export function generateSecurePassword(): string {
    const length = 12;
    const uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const lowercase = "abcdefghijklmnopqrstuvwxyz";
    const numbers = "0123456789";
    const special = "!@#$%^&*";
    const charset = uppercase + lowercase + numbers + special;
    
    let password = "";
    
    // Ensure at least one of each required character type
    password += uppercase[Math.floor(Math.random() * uppercase.length)];
    password += lowercase[Math.floor(Math.random() * lowercase.length)];
    password += numbers[Math.floor(Math.random() * numbers.length)];
    password += special[Math.floor(Math.random() * special.length)];
    
    // Fill the rest randomly
    for (let i = password.length; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * charset.length);
        password += charset[randomIndex];
    }
    
    // Shuffle the password to avoid predictable pattern
    return password.split('').sort(() => Math.random() - 0.5).join('');
}

export const getPassword = (configuredPassword: string | PasswordType | undefined): string => {
    if (!configuredPassword) {
        return generateSecurePassword();
    }
    
    if (configuredPassword === PasswordType.AutoGenerated) {
        return generateSecurePassword();
    }
    
    return configuredPassword;
};